apiVersion: v1
kind: ServiceAccount
metadata:
  name: glance
  namespace: glance
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: glance-reader
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: ["longhorn.io"]
    resources: ["volumes", "nodes", "replicas"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: glance-reader
subjects:
  - kind: ServiceAccount
    name: glance
    namespace: glance
roleRef:
  kind: ClusterRole
  name: glance-reader
  apiGroup: rbac.authorization.k8s.io
