---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: s3-backup-secret
  namespace: database
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBlx38SDYwGRHwir5gmjo1HqvgGgqPqyyazA0v98FFpoo2oM8/hYkTaBzz3FoowVRD+PX/1pTtrMoP4JoUxKrw4ImBwWBa9bI/Mkktxsxuu471wrWBM67XomMvIQ4yuNi2Y6c7MbupX1PvZhq8oIMW08wH3/K9/lhlO3vE/xJMZ6Iuy+ItV1GfhRF7Jz+SfKmKbggOei2ZshAmSWlAWu/asflyPknZ/6kHR9Y9YN3CkRVjKLfG2JBNGBNzr2nyJ0EJcXz/FDUUhxeqckz+26qC19FrHwuJipPNMjonHVp+gsJKz5n1PO3MpChxYV5p1yacpjzs/iJQYsumSaRwHRkrYUDI1EXtybeYVVX1UJnlgDL0HNRc1uVFAqCSSZhuPUdDxloKqoy8vDmiPsQg+h1y09EKbFEaJXgAshmYbh6mInlv5RP/UpNoxZgTl58YxkIM1QM/3vime3jPscaqKvDU6sQKsGE4wLwKJV+isF6LnW7QRgdY47jdq9jangjP69a07CKDjdQVh6cdQEtdciGmu9VBXt5M5Yio/ZDfX0gbXBSbUG43q3/ieSMksGWixJFEqo7dZSGkttXORvqdOhXEFES04/gcYt8L+r2SdOGVStZO4OlK89wDMrVezJmqViKyYBFOB9OJ0ozj/a7Y4z15bd+kbXGdkQ7YehyTnfAaw+hVwjtDyi0JG0bpFhKsaowl6Gh8D+X2EtqCmb/tdAst7CTxHtQ==
    AWS_SECRET_ACCESS_KEY: AgB4C7l4EvC9HxT4uVETntFMGyMZtT8lA3l5Q7rdU6EKcruulSTIxlGhpsVMgfOXnr7muWpkcVj14OoKyjnenhfkKD/I2wyOP97xwEvLRbh/IPveoV0Vvq014W0+CocWroCFOMyOD93YJOqeZOYLc93aKRWlzz5WIUhIrJjBg79zH+vlM7z47m50xTNXa/Hrw+s2IPWFMPN7jfivySrAZQdYU+sZXzUqxELu9/SzdU9KIdz0qQU8dXYpn44USnIYAmEdw4lYJ6rVOF7d3Qsq5+dnp3TmLIx3iWXEu4xur3hdbARICvGqaHm5F+4+fZZcXeYwE342gA4EP2p93AXRVZZfa6pGtb/WgN7rbtjHT9JEMCUvw9H3iifIJNGBnbeSUIfqaTIehPwL/Gxwb9945cvo30zFdkUP6sQy8HGKrFlO+WONGso17q+BnwYrtWL/w4jxcxm23ew+gay/H9pQYAgYQS+REU0r2GZkd2R2B8l+hUQHmF+YPnKq0AgC/p/TPoDwX1ViWHNqDcB/LL6ZO873Ln8rQL5wTS2/mE1MDqJI0Wel3lntQJgph0N/dTrKf6DDXP8wqErIEx2N9ozCDihCo058dHC4vApTO1iVNtJRAa5MPqtmiQNo0KWN/1aXXtokRjUI4/NQwDZwwvb1RfdbjAHVBeHoiKcl8v5ywapAXk5DlwSiYYC82ylzDi8exoVsrkBatftNleCZC2UAdOs80T4hWd7eCW4rgrnU4Q0boAS8i1fDqhA9M94=
  template:
    metadata:
      creationTimestamp: null
      name: s3-backup-secret
      namespace: database
    type: Opaque
