# Gitea Runner 설정
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-runner-config
  namespace: gitea
data:
  config.yaml: |
    log:
      level: info
    runner:
      file: /data/.runner
      capacity: 1
      timeout: 3h
    container:
      network: bridge
      privileged: false
      docker_host: unix:///var/run/user/1000/docker.sock
    cache:
      enabled: true
    host:
      workdir_parent: /data/cache
