apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-services
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitea.local.example.com/jw/homelab-infra.git
    targetRevision: main
    path: k8s/external
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
