apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-runner
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://gitea.local.example.com/jw/homelab-infra.git'
    path: k8s/github-runner
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: github-runner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
