apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alerting-rules.yaml
  - httproute.yaml
  - longhorn-servicemonitor.yaml
  - pve-exporter.yaml
  - truenas-exporter.yaml
  - sealed-pve-exporter.yaml
