apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-nfs-pv
spec:
  capacity:
    storage: 10Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    # truenas IP address
    server: 192.168.1.11
    path: /mnt/hdd-pool/Photos
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-nfs-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Ti
  volumeName: immich-nfs-pv
